export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_RESET_MESSAGE = "LOGIN_RESET_MESSAGE";
export const LOGOUT = "LOGOUT";

export const CLEAR_LOADING_STATE = "CLEAR_LOADING_STATE";

// Master
export const FETCH_MASTER_REQUEST = "FETCH_MASTER_REQUEST";
export const FETCH_MASTER_SUCCESS = "FETCH_MASTER_SUCCESS";
export const FETCH_MASTER_FAILED = "FETCH_MASTER_FAILED";

// Templates
export const FETCH_TEMPLATES_REQUEST = "FETCH_TEMPLATES_REQUEST";
export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS";
export const FETCH_TEMPLATES_FAILED = "FETCH_TEMPLATES_FAILED";

// Template Details
export const FETCH_TEMPLATE_VIEW_REQUEST = "FETCH_TEMPLATE_VIEW_REQUEST";
export const FETCH_TEMPLATE_VIEW_SUCCESS = "FETCH_TEMPLATE_VIEW_SUCCESS";
export const FETCH_TEMPLATE_VIEW_FAILED = "FETCH_TEMPLATE_VIEW_FAILED";

// Template Selected
export const FETCH_TEMPLATE_SELECTED_REQUEST =
  "FETCH_TEMPLATE_SELECTED_REQUEST";
export const FETCH_TEMPLATE_SELECTED_SUCCESS =
  "FETCH_TEMPLATE_SELECTED_SUCCESS";
export const FETCH_TEMPLATE_SELECTED_FAILED = "FETCH_TEMPLATE_SELECTED_FAILED";

// Create Template
export const CREATE_TEMPLATE_DETAIL_REQUEST = "CREATE_TEMPLATE_DETAIL_REQUEST";
export const CREATE_TEMPLATE_DETAIL_SUCCESS = "CREATE_TEMPLATE_DETAIL_SUCCESS";
export const CREATE_TEMPLATE_DETAIL_FAILED = "CREATE_TEMPLATE_DETAIL_FAILED";

// Remove Template
export const REMOVE_TEMPLATE_DETAIL_REQUEST = "REMOVE_TEMPLATE_DETAIL_REQUEST";
export const REMOVE_TEMPLATE_DETAIL_SUCCESS = "REMOVE_TEMPLATE_DETAIL_SUCCESS";
export const REMOVE_TEMPLATE_DETAIL_FAILED = "REMOVE_TEMPLATE_DETAIL_FAILED";

// Forms
export const FETCH_FORMS_REQUEST = "FETCH_FORMS_REQUEST";
export const FETCH_FORMS_SUCCESS = "FETCH_FORMS_SUCCESS";
export const FETCH_FORMS_FAILED = "FETCH_FORMS_FAILED";

// Form Detail
export const FETCH_FORM_DETAILS_REQUEST = "FETCH_FORM_DETAILS_REQUEST";
export const FETCH_FORM_DETAILS_SUCCESS = "FETCH_FORM_DETAILS_SUCCESS";
export const FETCH_FORM_DETAILS_FAILED = "FETCH_FORM_DETAILS_FAILED";

// Form Details Selected
export const FETCH_FORM_DETAILS_SELECTED_REQUEST =
  "FETCH_FORM_DETAILS_SELECTED_REQUEST";
export const FETCH_FORM_DETAILS_SELECTED_SUCCESS =
  "FETCH_FORM_DETAILS_SELECTED_SUCCESS";
export const FETCH_FORM_DETAILS_SELECTED_FAILED =
  "FETCH_FORM_DETAILS_SELECTED_FAILED";

// Create Form Detail
export const CREATE_FORM_DETAIL_REQUEST = "CREATE_FORM_DETAIL_REQUEST";
export const CREATE_FORM_DETAIL_SUCCESS = "CREATE_FORM_DETAIL_SUCCESS";
export const CREATE_FORM_DETAIL_FAILED = "CREATE_FORM_DETAIL_FAILED";

// Remove Form Detail
export const REMOVE_FORM_DETAIL_REQUEST = "REMOVE_FORM_DETAIL_REQUEST";
export const REMOVE_FORM_DETAIL_SUCCESS = "REMOVE_FORM_DETAIL_SUCCESS";
export const REMOVE_FORM_DETAIL_FAILED = "REMOVE_FORM_DETAIL_FAILED";

// View Mode
export const FETCH_VIEW_MODE = "FETCH_VIEW_MODE";
export const SET_VIEW_MODE = "SET_VIEW_MODE";
