export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_RESET_MESSAGE = "LOGIN_RESET_MESSAGE";
export const LOGOUT = "LOGOUT";

export const CLEAR_LOADING_STATE = "CLEAR_LOADING_STATE";

// Master
export const FETCH_MASTER_REQUEST = "FETCH_MASTER_REQUEST";
export const FETCH_MASTER_SUCCESS = "FETCH_MASTER_SUCCESS";
export const FETCH_MASTER_FAILED = "FETCH_MASTER_FAILED";

// Combined
export const FETCH_COMBINED_REQUEST = "FETCH_COMBINED_REQUEST";
export const FETCH_COMBINED_SUCCESS = "FETCH_COMBINED_SUCCESS";
export const FETCH_COMBINED_FAILED = "FETCH_COMBINED_FAILED";

// Hierarchy
export const FETCH_HIERARCHY_REQUEST = "FETCH_HIERARCHY_REQUEST";
export const FETCH_HIERARCHY_SUCCESS = "FETCH_HIERARCHY_SUCCESS";
export const FETCH_HIERARCHY_FAILED = "FETCH_HIERARCHY_FAILED";

// Templates
export const FETCH_TEMPLATES_REQUEST = "FETCH_TEMPLATES_REQUEST";
export const FETCH_TEMPLATES_SUCCESS = "FETCH_TEMPLATES_SUCCESS";
export const FETCH_TEMPLATES_FAILED = "FETCH_TEMPLATES_FAILED";
export const RESET_TEMPLATES = "RESET_TEMPLATES";

// Template Details
export const FETCH_TEMPLATE_VIEW_REQUEST = "FETCH_TEMPLATE_VIEW_REQUEST";
export const FETCH_TEMPLATE_VIEW_SUCCESS = "FETCH_TEMPLATE_VIEW_SUCCESS";
export const FETCH_TEMPLATE_VIEW_FAILED = "FETCH_TEMPLATE_VIEW_FAILED";

// Template Selected
export const FETCH_TEMPLATE_SELECTED_REQUEST =
  "FETCH_TEMPLATE_SELECTED_REQUEST";
export const FETCH_TEMPLATE_SELECTED_SUCCESS =
  "FETCH_TEMPLATE_SELECTED_SUCCESS";
export const FETCH_TEMPLATE_SELECTED_FAILED = "FETCH_TEMPLATE_SELECTED_FAILED";

// Reset Selected
export const RESET_TEMPLATE_SELECTED = "RESET_TEMPLATE_SELECTED";

// Create Template
export const CREATE_TEMPLATE_DETAIL_REQUEST = "CREATE_TEMPLATE_DETAIL_REQUEST";
export const CREATE_TEMPLATE_DETAIL_SUCCESS = "CREATE_TEMPLATE_DETAIL_SUCCESS";
export const CREATE_TEMPLATE_DETAIL_FAILED = "CREATE_TEMPLATE_DETAIL_FAILED";

// Remove All Template
export const REMOVE_ALL_TEMPLATE_DETAIL = "REMOVE_ALL_TEMPLATE_DETAIL";

export const REMOVE_TEMPLATE_DETAIL_REQUEST = "REMOVE_TEMPLATE_DETAIL_REQUEST";
export const REMOVE_TEMPLATE_DETAIL_SUCCESS = "REMOVE_TEMPLATE_DETAIL_SUCCESS";
export const REMOVE_TEMPLATE_DETAIL_FAILED = "REMOVE_TEMPLATE_DETAIL_FAILED";

// Forms
export const FETCH_FORMS_REQUEST = "FETCH_FORMS_REQUEST";
export const FETCH_FORMS_SUCCESS = "FETCH_FORMS_SUCCESS";
export const FETCH_FORMS_FAILED = "FETCH_FORMS_FAILED";

// Form Selected
export const SET_FORM_SELECTED = "SET_FORM_SELECTED";
export const RESET_FORM_SELECTED = "RESET_FORM_SELECTED";

// Form Detail
export const FETCH_FORM_DETAILS_REQUEST = "FETCH_FORM_DETAILS_REQUEST";
export const FETCH_FORM_DETAILS_SUCCESS = "FETCH_FORM_DETAILS_SUCCESS";
export const FETCH_FORM_DETAILS_FAILED = "FETCH_FORM_DETAILS_FAILED";

// Create New Form Detail
export const CREATE_NEW_FORM_DETAILS_REQUEST =
  "CREATE_NEW_FORM_DETAILS_REQUEST";
export const CREATE_NEW_FORM_DETAILS_SUCCESS =
  "CREATE_NEW_FORM_DETAILS_SUCCESS";
export const CREATE_NEW_FORM_DETAILS_FAILED = "CREATE_NEW_FORM_DETAILS_FAILED";

// Create Form Detail
export const CREATE_FORM_DETAIL_REQUEST = "CREATE_FORM_DETAIL_REQUEST";
export const CREATE_FORM_DETAIL_SUCCESS = "CREATE_FORM_DETAIL_SUCCESS";
export const CREATE_FORM_DETAIL_FAILED = "CREATE_FORM_DETAIL_FAILED";

// UPDATE Form Detail
export const UPDATE_FORM_DETAILS_REQUEST = "UPDATE_FORM_DETAILS_REQUEST";
export const UPDATE_FORM_DETAILS_SUCCESS = "UPDATE_FORM_DETAILS_SUCCESS";
export const UPDATE_FORM_DETAILS_FAILED = "UPDATE_FORM_DETAILS_FAILED";

// Remove All Form Detail
export const REMOVE_ALL_FORM_DETAIL = "REMOVE_ALL_FORM_DETAIL";

// Form Details Selected
export const FETCH_FORM_DETAILS_SELECTED_REQUEST =
  "FETCH_FORM_DETAILS_SELECTED_REQUEST";
export const FETCH_FORM_DETAILS_SELECTED_SUCCESS =
  "FETCH_FORM_DETAILS_SELECTED_SUCCESS";
export const FETCH_FORM_DETAILS_SELECTED_FAILED =
  "FETCH_FORM_DETAILS_SELECTED_FAILED";

// View Mode
export const FETCH_VIEW_MODE = "FETCH_VIEW_MODE";
export const SET_VIEW_MODE = "SET_VIEW_MODE";

// Reports
export const FETCH_REPORTS_REQUEST = "FETCH_REPORTS_REQUEST";
export const FETCH_REPORTS_SUCCESS = "FETCH_REPORTS_SUCCESS";
export const FETCH_REPORTS_FAILED = "FETCH_REPORTS_FAILED";

export const CREATE_REPORTS_REQUEST = "CREATE_REPORTS_REQUEST";
export const CREATE_REPORTS_SUCCESS = "CREATE_REPORTS_SUCCESS";
export const CREATE_REPORTS_FAILED = "CREATE_REPORTS_FAILED";

// Stock Position Report
export const CREATE_STOCK_POSITION_REQUEST = "CREATE_STOCK_POSITION_REQUEST";
export const CREATE_STOCK_POSITION_SUCCESS = "CREATE_STOCK_POSITION_SUCCESS";
export const CREATE_STOCK_POSITION_FAILED = "CREATE_STOCK_POSITION_FAILED";

export const FETCH_STOCK_POSITION_REQUEST = "FETCH_STOCK_POSITION_REQUEST";
export const FETCH_STOCK_POSITION_SUCCESS = "FETCH_STOCK_POSITION_SUCCESS";
export const FETCH_STOCK_POSITION_FAILED = "FETCH_STOCK_POSITION_FAILED";

// Waste
export const FETCH_COMPARE_WASTE_REQUEST = "FETCH_COMPARE_WASTE_REQUEST";
export const FETCH_COMPARE_WASTE_SUCCESS = "FETCH_COMPARE_WASTE_SUCCESS";
export const FETCH_COMPARE_WASTE_FAILED = "FETCH_COMPARE_WASTE_FAILED";

// Final Forms
export const FETCH_FINAL_FORM_REQUEST = "FETCH_FINAL_FORM_REQUEST";
export const FETCH_FINAL_FORM_SUCCESS = "FETCH_FINAL_FORM_SUCCESS";
export const FETCH_FINAL_FORM_FAILED = "FETCH_FINAL_FORM_FAILED";

export const CREATE_FINAL_FORM_REQUEST = "CREATE_FINAL_FORM_REQUEST";
export const CREATE_FINAL_FORM_SUCCESS = "CREATE_FINAL_FORM_SUCCESS";
export const CREATE_FINAL_FORM_FAILED = "CREATE_FINAL_FORM_FAILED";

// Testing
export const FETCH_TESTING_OUTLET_REQUEST = "FETCH_TESTING_OUTLET_REQUEST";
export const FETCH_TESTING_OUTLET_SUCCESS = "FETCH_TESTING_OUTLET_SUCCESS";
export const FETCH_TESTING_OUTLET_FAILED = "FETCH_TESTING_OUTLET_FAILED";

export const FETCH_TESTING_STAFF_FORMS_REQUEST =
  "FETCH_TESTING_STAFF_FORMS_REQUEST";
export const FETCH_TESTING_STAFF_FORMS_SUCCESS =
  "FETCH_TESTING_STAFF_FORMS_SUCCESS";
export const FETCH_TESTING_STAFF_FORMS_FAILED =
  "FETCH_TESTING_STAFF_FORMS_FAILED";

export const FETCH_TESTING_FORM_BY_STAFF_REQUEST =
  "FETCH_TESTING_FORM_BY_STAFF_REQUEST";
export const FETCH_TESTING_FORM_BY_STAFF_SUCCESS =
  "FETCH_TESTING_FORM_BY_STAFF_SUCCESS";
export const FETCH_TESTING_FORM_BY_STAFF_FAILED =
  "FETCH_TESTING_FORM_BY_STAFF_FAILED";

export const CREATE_DAILY_FORM_REPORT = "CREATE_DAILY_FORM_REPORT";
